import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity: String = "androidx.activity:activity:_"

    public const val activity_ktx: String = "androidx.activity:activity-ktx:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val animation: String = "androidx.compose.animation:animation:_"

    public const val foundation: String = "androidx.compose.foundation:foundation:_"

    public const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    public const val material_icons_core: String = "androidx.compose.material:material-icons-core:_"

    public const val material_ripple: String = "androidx.compose.material:material-ripple:_"

    public const val androidx_compose_runtime_runtime: String = "androidx.compose.runtime:runtime:_"

    public const val ui: String = "androidx.compose.ui:ui:_"

    public const val ui_graphics: String = "androidx.compose.ui:ui-graphics:_"

    public const val ui_text: String = "androidx.compose.ui:ui-text:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val constraintlayout_compose: String =
            "androidx.constraintlayout:constraintlayout-compose:_"

    public const val androidx_core_core: String = "androidx.core:core:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val fragment: String = "androidx.fragment:fragment:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val lifecycle_livedata: String = "androidx.lifecycle:lifecycle-livedata:_"

    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    public const val lifecycle_process: String = "androidx.lifecycle:lifecycle-process:_"

    public const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"

    public const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    public const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val junit_ktx: String = "androidx.test.ext:junit-ktx:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val glide: String = "com.github.bumptech.glide:glide:_"

    public const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    public const val retrofit2_kotlinx_serialization_converter: String =
            "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val kotlinx_serialization_json: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-json:_"
}
